### ISSUE TITLE
Fix permanently margin and border issues with area below gridTransaction details 

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1483] opened 2021-01-04 14:13 UTC
- Seems that from time to time borders are missing in this area because of the current layout:
![Screenshot 2021-01-04 at 15 09 27](https://user-images.githubusercontent.com/33226956/103543457-d927de00-4e9e-11eb-9fd6-bb206446e6ee.png)
- Problem seem to be fact that we add borders based on other elements present but i would suggest that we implement flexbox with row-gap so that in the future when we decide to add some new window we don't have to worry about this and they will just stack on top of each other.

**Comment by KadenZipfel** [comment] 2021-01-04 18:43
Closing as it's a duplicate of https://github.com/protofire/omen-exchange/issues/1484

**Closed by KadenZipfel** 2021-01-04 18:43 UTC
Labels: enhancement
