### ISSUE TITLE
cDAI currency causing problems when trading markets where you have a cDAI position

### ISSUE THREAD

**Issue by skyminert** [protofire/omen-exchange#1146] opened 2020-10-05 19:32 UTC
On a market where i own shares, and I got to "Sell" page.  It shows my shares in my Wallet Balance, but when you click on blue linked shares in order to "Sell all of the selected outcome's shares." The amount doesn't fill the Shares field just underneath.
This market is with currency"cDAI".  It's not filling.  I think other currencies are filling the box when you click the amount.

**Comment by pimato** [comment] 2020-10-05 21:37
I can replicate that on rinkeby:

1) Go to Market: https://dxtest.eth.link/#/0xe8d93e22c5ffc64aa9f27d21c7c6164928e8ebce/buy
2) Try to buy/sell by clicking on the available balance like this:
<img width="636" alt="Bildschirmfoto 2020-10-05 um 23 36 16" src="https://user-images.githubusercontent.com/5337809/95134714-a23d1180-0763-11eb-97bd-b86a67dcfe2f.png">
3) **BUG: The inputfield should have been filled with the available balance but it is empty**

**Comment by KadenZipfel** [comment] 2020-10-05 22:25
Interestingly, although I can reproduce on dxtest.eth, I cannot reproduce locally on the master branch. So it seems maybe whatever was causing this has already been resolved since the content hash of dxtest.eth was last set.

**Comment by KadenZipfel** [comment] 2020-10-08 21:49
Closing as the problem seems to be resolved (doesn't even happen on dxtest.eth since the last update).

**Closed by KadenZipfel** 2020-10-08 21:49 UTC
Labels: bug, priority:high
